import type { City } from '@/types'

export const cities: City[] = [
  // Europe (30)
  {
    id: 'london',
    name: 'London',
    country: 'United Kingdom',
    region: 'europe',
    coordinates: { lat: 51.5074, lng: -0.1278 },
    timezone: 'Europe/London',
    meetupLocation: {
      name: 'The Persian Kitchen',
      address: '25 Westbourne Grove, London W2 4UA',
      coordinates: { lat: 51.5153, lng: -0.1912 },
    },
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    region: 'europe',
    coordinates: { lat: 48.8566, lng: 2.3522 },
    timezone: 'Europe/Paris',
    meetupLocation: {
      name: 'Cafe de Flore',
      address: '172 Boulevard Saint-Germain, 75006 Paris',
      coordinates: { lat: 48.854, lng: 2.3326 },
    },
  },
  {
    id: 'berlin',
    name: 'Berlin',
    country: 'Germany',
    region: 'europe',
    coordinates: { lat: 52.52, lng: 13.405 },
    timezone: 'Europe/Berlin',
    posterUrl: '/posters/Berlin.jpeg',
    meetupLocation: {
      name: 'Kurfurstendamm / Joachimstaler Str.',
      address: 'Kurfurstendamm / Joachimstaler Str., Berlin',
      coordinates: { lat: 52.5046, lng: 13.3326 },
    },
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    region: 'europe',
    coordinates: { lat: 52.3676, lng: 4.9041 },
    timezone: 'Europe/Amsterdam',
    meetupLocation: {
      name: 'Vondelpark',
      address: 'Vondelpark, Amsterdam',
      coordinates: { lat: 52.358, lng: 4.8686 },
    },
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    country: 'Spain',
    region: 'europe',
    coordinates: { lat: 41.3851, lng: 2.1734 },
    timezone: 'Europe/Madrid',
    posterUrl: '/posters/Barcelona.jpeg',
    meetupLocation: {
      name: 'Placa de Catalunya',
      address: 'Placa de Catalunya, 08002 Barcelona',
      coordinates: { lat: 41.3870, lng: 2.1700 },
    },
  },
  {
    id: 'rome',
    name: 'Rome',
    country: 'Italy',
    region: 'europe',
    coordinates: { lat: 41.9028, lng: 12.4964 },
    timezone: 'Europe/Rome',
    posterUrl: '/posters/Rome.png',
    meetupLocation: {
      name: 'Piazzale Ugo La Malfa',
      address: 'Piazzale Ugo La Malfa, Roma',
      coordinates: { lat: 41.9145, lng: 12.4723 },
    },
  },
  {
    id: 'vienna',
    name: 'Vienna',
    country: 'Austria',
    region: 'europe',
    coordinates: { lat: 48.2082, lng: 16.3738 },
    timezone: 'Europe/Vienna',
    posterUrl: '/posters/Vienna, Austria.jpg',
    meetupLocation: {
      name: 'Heldenplatz',
      address: 'Heldenplatz, 1010 Wien',
      coordinates: { lat: 48.2066, lng: 16.3633 },
    },
  },
  {
    id: 'prague',
    name: 'Prague',
    country: 'Czech Republic',
    region: 'europe',
    coordinates: { lat: 50.0755, lng: 14.4378 },
    timezone: 'Europe/Prague',
    meetupLocation: {
      name: 'Old Town Square',
      address: 'Staromestske namesti, 110 00 Praha',
      coordinates: { lat: 50.0875, lng: 14.4213 },
    },
  },
  {
    id: 'stockholm',
    name: 'Stockholm',
    country: 'Sweden',
    region: 'europe',
    coordinates: { lat: 59.3293, lng: 18.0686 },
    timezone: 'Europe/Stockholm',
    posterUrl: '/posters/Stockholm.jpeg',
    meetupLocation: {
      name: 'Norra Bantorget',
      address: 'Norra Bantorget, Stockholm',
      coordinates: { lat: 59.3340, lng: 18.0583 },
    },
  },
  {
    id: 'dublin',
    name: 'Dublin',
    country: 'Ireland',
    region: 'europe',
    coordinates: { lat: 53.3498, lng: -6.2603 },
    timezone: 'Europe/Dublin',
    meetupLocation: {
      name: 'Temple Bar',
      address: 'Temple Bar, Dublin 2',
      coordinates: { lat: 53.3455, lng: -6.2634 },
    },
  },
  {
    id: 'brussels',
    name: 'Brussels',
    country: 'Belgium',
    region: 'europe',
    coordinates: { lat: 50.8503, lng: 4.3517 },
    timezone: 'Europe/Brussels',
    posterUrl: '/posters/Brussels - Jan 31.jpg',
    meetupLocation: {
      name: 'Av. Franklin Roosevelt 15',
      address: 'Av. Franklin Roosevelt 15, 1050 Ixelles',
      coordinates: { lat: 50.8137, lng: 4.3809 },
    },
  },
  {
    id: 'munich',
    name: 'Munich',
    country: 'Germany',
    region: 'europe',
    coordinates: { lat: 48.1351, lng: 11.582 },
    timezone: 'Europe/Berlin',
    posterUrl: '/posters/Munich Jan 31.jpeg',
    meetupLocation: {
      name: 'Gartnerplatz',
      address: 'Gartnerplatz, 80469 Munchen',
      coordinates: { lat: 48.1306, lng: 11.5769 },
    },
  },
  {
    id: 'zurich',
    name: 'Zurich',
    country: 'Switzerland',
    region: 'europe',
    coordinates: { lat: 47.3769, lng: 8.5417 },
    timezone: 'Europe/Zurich',
    meetupLocation: {
      name: 'Zurich Lake',
      address: 'Zurichsee, Zurich',
      coordinates: { lat: 47.3667, lng: 8.55 },
    },
  },
  {
    id: 'copenhagen',
    name: 'Copenhagen',
    country: 'Denmark',
    region: 'europe',
    coordinates: { lat: 55.6761, lng: 12.5683 },
    timezone: 'Europe/Copenhagen',
    meetupLocation: {
      name: 'Nyhavn',
      address: 'Nyhavn, 1051 Kobenhavn',
      coordinates: { lat: 55.6798, lng: 12.5914 },
    },
  },
  {
    id: 'oslo',
    name: 'Oslo',
    country: 'Norway',
    region: 'europe',
    coordinates: { lat: 59.9139, lng: 10.7522 },
    timezone: 'Europe/Oslo',
    posterUrl: '/posters/Oslo.jpeg',
    meetupLocation: {
      name: 'Jernbanetorget to Eidsvolls Plass',
      address: 'Jernbanetorget to Eidsvolls Plass, Oslo',
      coordinates: { lat: 59.9127, lng: 10.7518 },
    },
  },
  // New Europe cities from posters
  {
    id: 'manchester',
    name: 'Manchester',
    country: 'United Kingdom',
    region: 'europe',
    coordinates: { lat: 53.4808, lng: -2.2426 },
    timezone: 'Europe/London',
    posterUrl: '/posters/Manchester.jpeg',
    meetupLocation: {
      name: 'Central Library',
      address: "St Peter's Square, Manchester M2 5PD",
      coordinates: { lat: 53.4784, lng: -2.2451 },
    },
  },
  {
    id: 'sheffield',
    name: 'Sheffield',
    country: 'United Kingdom',
    region: 'europe',
    coordinates: { lat: 53.3811, lng: -1.4701 },
    timezone: 'Europe/London',
    posterUrl: '/posters/Sheffield.jpeg',
    meetupLocation: {
      name: "Barker's Pool",
      address: "Barker's Pool, Sheffield S1 2JA",
      coordinates: { lat: 53.3814, lng: -1.4746 },
    },
  },
  {
    id: 'belfast',
    name: 'Belfast',
    country: 'United Kingdom',
    region: 'europe',
    coordinates: { lat: 54.5973, lng: -5.9301 },
    timezone: 'Europe/London',
    posterUrl: '/posters/Belfast.jpeg',
    meetupLocation: {
      name: 'Belfast City Hall',
      address: 'Donegall Square N, Belfast BT1 5GS',
      coordinates: { lat: 54.5964, lng: -5.9302 },
    },
  },
  {
    id: 'cambridge',
    name: 'Cambridge',
    country: 'United Kingdom',
    region: 'europe',
    coordinates: { lat: 52.2053, lng: 0.1218 },
    timezone: 'Europe/London',
    posterUrl: '/posters/Cambridge.png',
    meetupLocation: {
      name: 'Market Square',
      address: 'Market Square, Cambridge',
      coordinates: { lat: 52.2054, lng: 0.1183 },
    },
  },
  {
    id: 'frankfurt',
    name: 'Frankfurt',
    country: 'Germany',
    region: 'europe',
    coordinates: { lat: 50.1109, lng: 8.6821 },
    timezone: 'Europe/Berlin',
    posterUrl: '/posters/Frankfurt.jpeg',
    meetupLocation: {
      name: 'Rathenauplatz',
      address: 'Rathenauplatz (Goetheplatz), Frankfurt',
      coordinates: { lat: 50.1136, lng: 8.6743 },
    },
  },
  {
    id: 'hamburg',
    name: 'Hamburg',
    country: 'Germany',
    region: 'europe',
    coordinates: { lat: 53.5511, lng: 9.9937 },
    timezone: 'Europe/Berlin',
    posterUrl: '/posters/Hamburg.jpeg',
    meetupLocation: {
      name: 'Kurt-Schumacher-Allee 10',
      address: 'Kurt-Schumacher-Allee 10, Hamburg',
      coordinates: { lat: 53.5530, lng: 10.0065 },
    },
  },
  {
    id: 'hannover',
    name: 'Hannover',
    country: 'Germany',
    region: 'europe',
    coordinates: { lat: 52.3759, lng: 9.7320 },
    timezone: 'Europe/Berlin',
    posterUrl: '/posters/Hannover.jpeg',
    meetupLocation: {
      name: 'Neues Rathaus',
      address: 'Trammplatz 2, 30159 Hannover',
      coordinates: { lat: 52.3676, lng: 9.7385 },
    },
  },
  {
    id: 'karlsruhe',
    name: 'Karlsruhe',
    country: 'Germany',
    region: 'europe',
    coordinates: { lat: 49.0069, lng: 8.4037 },
    timezone: 'Europe/Berlin',
    posterUrl: '/posters/Karlsruhe, Germany.jpeg',
    meetupLocation: {
      name: 'Kronenplatz to Marktplatz',
      address: 'Kronenplatz to Marktplatz, Karlsruhe',
      coordinates: { lat: 49.0094, lng: 8.4044 },
    },
  },
  {
    id: 'stuttgart',
    name: 'Stuttgart',
    country: 'Germany',
    region: 'europe',
    coordinates: { lat: 48.7758, lng: 9.1829 },
    timezone: 'Europe/Berlin',
    posterUrl: '/posters/Stuttgart.jpeg',
    meetupLocation: {
      name: 'Lautenschlagerstrasse',
      address: 'Lautenschlagerstrasse, 70173 Stuttgart',
      coordinates: { lat: 48.7831, lng: 9.1820 },
    },
  },
  {
    id: 'grenoble',
    name: 'Grenoble',
    country: 'France',
    region: 'europe',
    coordinates: { lat: 45.1885, lng: 5.7245 },
    timezone: 'Europe/Paris',
    posterUrl: '/posters/Grenoble, France.jpg',
    meetupLocation: {
      name: 'Place Victor Hugo',
      address: 'Place Victor Hugo, 38000 Grenoble',
      coordinates: { lat: 45.1875, lng: 5.7246 },
    },
  },
  {
    id: 'gothenburg',
    name: 'Gothenburg',
    country: 'Sweden',
    region: 'europe',
    coordinates: { lat: 57.7089, lng: 11.9746 },
    timezone: 'Europe/Stockholm',
    posterUrl: '/posters/Gothenburg, Sweden.jpeg',
    meetupLocation: {
      name: 'Gotaplatsen',
      address: 'Gotaplatsen, Gothenburg',
      coordinates: { lat: 57.6969, lng: 11.9797 },
    },
  },
  {
    id: 'stavanger',
    name: 'Stavanger',
    country: 'Norway',
    region: 'europe',
    coordinates: { lat: 58.9700, lng: 5.7331 },
    timezone: 'Europe/Oslo',
    posterUrl: '/posters/Stavanger, Norway.jpeg',
    meetupLocation: {
      name: 'Torget',
      address: 'Torget, Stavanger',
      coordinates: { lat: 58.9701, lng: 5.7305 },
    },
  },
  {
    id: 'odense',
    name: 'Odense',
    country: 'Denmark',
    region: 'europe',
    coordinates: { lat: 55.4038, lng: 10.4024 },
    timezone: 'Europe/Copenhagen',
    posterUrl: '/posters/Odense, Denmark.jpg',
    meetupLocation: {
      name: 'Grabrødre Plads',
      address: 'Grabrødre Plads 1, 5000 Odense',
      coordinates: { lat: 55.3962, lng: 10.3872 },
    },
  },
  {
    id: 'the-hague',
    name: 'The Hague',
    country: 'Netherlands',
    region: 'europe',
    coordinates: { lat: 52.0705, lng: 4.3007 },
    timezone: 'Europe/Amsterdam',
    posterUrl: '/posters/Holland.jpeg',
    meetupLocation: {
      name: 'Malieveld',
      address: 'Malieveld, Den Haag',
      coordinates: { lat: 52.0828, lng: 4.3245 },
    },
  },

  // North America (26)
  {
    id: 'new-york',
    name: 'New York',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 40.7128, lng: -74.006 },
    timezone: 'America/New_York',
    posterUrl: '/posters/NYC.jpeg',
    meetupLocation: {
      name: '1033 5th Avenue',
      address: '1033 5th Avenue, NYC (Between 84th & 85th St)',
      coordinates: { lat: 40.7794, lng: -73.9632 },
    },
  },
  {
    id: 'los-angeles',
    name: 'Los Angeles (Westwood)',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 34.0522, lng: -118.2437 },
    timezone: 'America/Los_Angeles',
    posterUrl: '/posters/Westwood LA.jpeg',
    meetupLocation: {
      name: 'Persian Square',
      address: 'Westwood Blvd, Los Angeles, CA 90024',
      coordinates: { lat: 34.0611, lng: -118.4466 },
    },
  },
  {
    id: 'san-francisco',
    name: 'San Francisco',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 37.7749, lng: -122.4194 },
    timezone: 'America/Los_Angeles',
    posterUrl: '/posters/San Francisco.jpeg',
    meetupLocation: {
      name: 'Golden Gate Bridge Gift Center',
      address: 'Golden Gate Bridge Gift Center, San Francisco, CA',
      coordinates: { lat: 37.8079, lng: -122.4750 },
    },
  },
  {
    id: 'toronto',
    name: 'Toronto',
    country: 'Canada',
    region: 'north-america',
    coordinates: { lat: 43.6532, lng: -79.3832 },
    timezone: 'America/Toronto',
    posterUrl: '/posters/Toronto.jpeg',
    meetupLocation: {
      name: 'Sankofa (Dundas) Square',
      address: 'Sankofa Square, Dundas & Yonge, Toronto',
      coordinates: { lat: 43.6561, lng: -79.3802 },
    },
  },
  {
    id: 'vancouver',
    name: 'Vancouver',
    country: 'Canada',
    region: 'north-america',
    coordinates: { lat: 49.2827, lng: -123.1207 },
    timezone: 'America/Vancouver',
    meetupLocation: {
      name: 'Stanley Park',
      address: 'Stanley Park, Vancouver, BC V6G 1Z4',
      coordinates: { lat: 49.3017, lng: -123.1417 },
    },
  },
  {
    id: 'chicago',
    name: 'Chicago',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 41.8781, lng: -87.6298 },
    timezone: 'America/Chicago',
    meetupLocation: {
      name: 'Millennium Park',
      address: '201 E Randolph St, Chicago, IL 60602',
      coordinates: { lat: 41.8827, lng: -87.6233 },
    },
  },
  {
    id: 'seattle',
    name: 'Seattle',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 47.6062, lng: -122.3321 },
    timezone: 'America/Los_Angeles',
    meetupLocation: {
      name: 'Pike Place Market',
      address: '85 Pike St, Seattle, WA 98101',
      coordinates: { lat: 47.6097, lng: -122.3422 },
    },
  },
  {
    id: 'boston',
    name: 'Boston',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 42.3601, lng: -71.0589 },
    timezone: 'America/New_York',
    meetupLocation: {
      name: 'Boston Common',
      address: 'Boston Common, Boston, MA 02108',
      coordinates: { lat: 42.3551, lng: -71.0656 },
    },
  },
  {
    id: 'miami',
    name: 'Miami',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 25.7617, lng: -80.1918 },
    timezone: 'America/New_York',
    meetupLocation: {
      name: 'South Beach',
      address: 'Ocean Dr, Miami Beach, FL 33139',
      coordinates: { lat: 25.7826, lng: -80.1341 },
    },
  },
  {
    id: 'montreal',
    name: 'Montreal',
    country: 'Canada',
    region: 'north-america',
    coordinates: { lat: 45.5017, lng: -73.5673 },
    timezone: 'America/Montreal',
    posterUrl: '/posters/Montreal English.jpg',
    meetupLocation: {
      name: 'Atwater Metro',
      address: 'Atwater Metro area, Montreal, QC',
      coordinates: { lat: 45.4897, lng: -73.5857 },
    },
  },
  {
    id: 'austin',
    name: 'Austin',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 30.2672, lng: -97.7431 },
    timezone: 'America/Chicago',
    meetupLocation: {
      name: 'Zilker Park',
      address: '2100 Barton Springs Rd, Austin, TX 78704',
      coordinates: { lat: 30.267, lng: -97.773 },
    },
  },
  {
    id: 'denver',
    name: 'Denver',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 39.7392, lng: -104.9903 },
    timezone: 'America/Denver',
    meetupLocation: {
      name: 'Civic Center Park',
      address: '101 14th Ave, Denver, CO 80204',
      coordinates: { lat: 39.7392, lng: -104.9847 },
    },
  },
  {
    id: 'portland',
    name: 'Portland',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 45.5051, lng: -122.675 },
    timezone: 'America/Los_Angeles',
    meetupLocation: {
      name: 'Pioneer Courthouse Square',
      address: '701 SW 6th Ave, Portland, OR 97204',
      coordinates: { lat: 45.5189, lng: -122.6795 },
    },
  },
  {
    id: 'san-diego',
    name: 'San Diego',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 32.7157, lng: -117.1611 },
    timezone: 'America/Los_Angeles',
    meetupLocation: {
      name: 'Balboa Park',
      address: '1549 El Prado, San Diego, CA 92101',
      coordinates: { lat: 32.7341, lng: -117.1446 },
    },
  },
  // New North America cities from posters
  {
    id: 'houston',
    name: 'Houston',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 29.7604, lng: -95.3698 },
    timezone: 'America/Chicago',
    posterUrl: '/posters/Houston - Sunday.jpg',
    meetupLocation: {
      name: 'Hermann Park',
      address: '6001 Fannin St, Houston, TX 77030',
      coordinates: { lat: 29.7138, lng: -95.3911 },
    },
  },
  {
    id: 'dallas',
    name: 'Dallas (Plano)',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 33.0198, lng: -96.6989 },
    timezone: 'America/Chicago',
    posterUrl: '/posters/Dallas (Plano), Texas.jpeg',
    meetupLocation: {
      name: '9700 Coit Rd',
      address: '9700 Coit Rd, Plano, TX',
      coordinates: { lat: 33.0356, lng: -96.7698 },
    },
  },
  {
    id: 'san-antonio',
    name: 'San Antonio',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 29.4241, lng: -98.4936 },
    timezone: 'America/Chicago',
    posterUrl: '/posters/San Antonio, Texas.jpeg',
    meetupLocation: {
      name: '4335 NW Loop 410',
      address: '4335 NW Loop 410, San Antonio, TX',
      coordinates: { lat: 29.5072, lng: -98.5677 },
    },
  },
  {
    id: 'nashville',
    name: 'Nashville',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 36.1627, lng: -86.7816 },
    timezone: 'America/Chicago',
    posterUrl: '/posters/Nashville, TN.jpeg',
    meetupLocation: {
      name: 'Estes Federal Building',
      address: '801 Broadway, Nashville, TN',
      coordinates: { lat: 36.1588, lng: -86.7787 },
    },
  },
  {
    id: 'wichita',
    name: 'Wichita',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 37.6872, lng: -97.3301 },
    timezone: 'America/Chicago',
    posterUrl: '/posters/Wichita, Kansas.jpeg',
    meetupLocation: {
      name: 'Keeper Of The Plains',
      address: '339 Veterans Pkwy, Wichita, KS',
      coordinates: { lat: 37.6840, lng: -97.3516 },
    },
  },
  {
    id: 'hartford',
    name: 'Hartford',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 41.7658, lng: -72.6734 },
    timezone: 'America/New_York',
    posterUrl: '/posters/Hartford, Connecticut.jpeg',
    meetupLocation: {
      name: 'State Capitol',
      address: '210 Capitol Ave, Hartford, CT',
      coordinates: { lat: 41.7642, lng: -72.6826 },
    },
  },
  {
    id: 'tempe',
    name: 'Tempe',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 33.4255, lng: -111.9400 },
    timezone: 'America/Phoenix',
    posterUrl: '/posters/Tempe, Arizona.jpg',
    meetupLocation: {
      name: '452 E University Dr',
      address: '452 E University Dr, Tempe, AZ',
      coordinates: { lat: 33.4217, lng: -111.9341 },
    },
  },
  {
    id: 'orlando',
    name: 'Orlando',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 28.5383, lng: -81.3792 },
    timezone: 'America/New_York',
    posterUrl: '/posters/Orlando.jpeg',
    meetupLocation: {
      name: 'Lake Eola',
      address: 'Lake Eola Park, Orlando, FL',
      coordinates: { lat: 28.5433, lng: -81.3736 },
    },
  },
  {
    id: 'irvine',
    name: 'Irvine',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 33.6846, lng: -117.8265 },
    timezone: 'America/Los_Angeles',
    posterUrl: '/posters/Irvine, CA.png',
    meetupLocation: {
      name: 'Culver & Barranca Pkwy',
      address: 'Culver & Barranca Pkwy, Irvine, CA',
      coordinates: { lat: 33.6897, lng: -117.8270 },
    },
  },
  {
    id: 'great-neck',
    name: 'Great Neck',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 40.8007, lng: -73.7285 },
    timezone: 'America/New_York',
    posterUrl: '/posters/Village Green Park, Great Neck.jpeg',
    meetupLocation: {
      name: 'Village Green Park',
      address: 'Village Green Park, Great Neck, NY',
      coordinates: { lat: 40.8007, lng: -73.7285 },
    },
  },
  {
    id: 'ottawa',
    name: 'Ottawa',
    country: 'Canada',
    region: 'north-america',
    coordinates: { lat: 45.4215, lng: -75.6972 },
    timezone: 'America/Toronto',
    posterUrl: '/posters/Ottawa - Feb 1.jpeg',
    meetupLocation: {
      name: 'Parliament Hill',
      address: 'Wellington St, Ottawa, ON',
      coordinates: { lat: 45.4236, lng: -75.7009 },
    },
  },
  {
    id: 'charlottetown',
    name: 'Charlottetown',
    country: 'Canada',
    region: 'north-america',
    coordinates: { lat: 46.2382, lng: -63.1311 },
    timezone: 'America/Halifax',
    posterUrl: '/posters/Charlottetown, PEI.jpeg',
    meetupLocation: {
      name: 'Cenotaph of Veterans',
      address: 'Cenotaph of Veterans, Charlottetown, PEI',
      coordinates: { lat: 46.2343, lng: -63.1268 },
    },
  },
  {
    id: 'prince-george',
    name: 'Prince George',
    country: 'Canada',
    region: 'north-america',
    coordinates: { lat: 53.9171, lng: -122.7497 },
    timezone: 'America/Vancouver',
    posterUrl: '/posters/Prince George, BC.jpeg',
    meetupLocation: {
      name: 'St. Michael Hall',
      address: 'St. Michael Hall, Prince George, BC',
      coordinates: { lat: 53.9171, lng: -122.7497 },
    },
  },
  {
    id: 'bellevue',
    name: 'Bellevue',
    country: 'United States',
    region: 'north-america',
    coordinates: { lat: 47.6101, lng: -122.2015 },
    timezone: 'America/Los_Angeles',
    posterUrl: '/posters/Washington State.jpeg',
    meetupLocation: {
      name: 'Bellevue Park',
      address: 'Bellevue Park, Bellevue, WA',
      coordinates: { lat: 47.6137, lng: -122.2067 },
    },
  },

  // Oceania (6)
  {
    id: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    region: 'oceania',
    coordinates: { lat: -33.8688, lng: 151.2093 },
    timezone: 'Australia/Sydney',
    posterUrl: '/posters/Sydney.jpeg',
    meetupLocation: {
      name: 'Hyde Park North',
      address: 'Hyde Park North, Sydney NSW 2000',
      coordinates: { lat: -33.8723, lng: 151.2109 },
    },
  },
  {
    id: 'melbourne',
    name: 'Melbourne',
    country: 'Australia',
    region: 'oceania',
    coordinates: { lat: -37.8136, lng: 144.9631 },
    timezone: 'Australia/Melbourne',
    meetupLocation: {
      name: 'Federation Square',
      address: 'Swanston St & Flinders St, Melbourne VIC 3000',
      coordinates: { lat: -37.8179, lng: 144.9691 },
    },
  },
  {
    id: 'auckland',
    name: 'Auckland',
    country: 'New Zealand',
    region: 'oceania',
    coordinates: { lat: -36.8485, lng: 174.7633 },
    timezone: 'Pacific/Auckland',
    posterUrl: '/posters/Auckland, NZ.jpeg',
    meetupLocation: {
      name: 'Western Park',
      address: 'Western Park, Ponsonby, Auckland',
      coordinates: { lat: -36.8587, lng: 174.7449 },
    },
  },
  {
    id: 'brisbane',
    name: 'Brisbane',
    country: 'Australia',
    region: 'oceania',
    coordinates: { lat: -27.4698, lng: 153.0251 },
    timezone: 'Australia/Brisbane',
    posterUrl: '/posters/Brisbane.jpeg',
    meetupLocation: {
      name: 'Reddacliff Place',
      address: 'Reddacliff Place, Brisbane QLD 4000',
      coordinates: { lat: -27.4697, lng: 153.0247 },
    },
  },
  {
    id: 'perth',
    name: 'Perth',
    country: 'Australia',
    region: 'oceania',
    coordinates: { lat: -31.9505, lng: 115.8605 },
    timezone: 'Australia/Perth',
    meetupLocation: {
      name: 'Kings Park',
      address: 'Fraser Ave, Perth WA 6005',
      coordinates: { lat: -31.9601, lng: 115.8426 },
    },
  },
  {
    id: 'wellington',
    name: 'Wellington',
    country: 'New Zealand',
    region: 'oceania',
    coordinates: { lat: -41.2865, lng: 174.7762 },
    timezone: 'Pacific/Auckland',
    meetupLocation: {
      name: 'Waterfront',
      address: 'Wellington Waterfront, Wellington 6011',
      coordinates: { lat: -41.2865, lng: 174.7811 },
    },
  },
]

export function getCityById(id: string): City | undefined {
  return cities.find((city) => city.id === id)
}

export function getCitiesByRegion(region: City['region']): City[] {
  return cities.filter((city) => city.region === region)
}

export const regionLabels: Record<City['region'], string> = {
  europe: 'Europe',
  'north-america': 'North America',
  oceania: 'Oceania',
}
