import type { Coordinates, EventStatus } from '@/types'

export interface RallyEvent {
  id: string
  cityId: string
  title: string
  description: string
  date: string
  startTime: string
  endTime?: string
  venue: string
  address: string
  coordinates: Coordinates
  theme?: string
  organizer?: string
  posterImage: string
  status: EventStatus
  eventUrl?: string
  facebookGroupUrl?: string
  rsvpUrl?: string
  instagramUrl?: string
  telegramUrl?: string
}

export const events: RallyEvent[] = [
  // Europe Events
  {
    id: 'berlin-jan-31',
    cityId: 'berlin',
    title: 'Stand with the People of Iran',
    description: 'Mass protest in central Berlin demanding an end to executions and political repression in Iran. Bring signs, flags, and your voice. The Iranian community in Berlin has been organizing weekly since 2022.',
    date: '2026-01-31',
    startTime: '14:00',
    endTime: '18:00',
    venue: 'Kurfurstendamm / Joachimstaler Str.',
    address: 'Kurfurstendamm / Joachimstaler Str., Berlin',
    coordinates: { lat: 52.5046, lng: 13.3326 },
    theme: 'Iranian Revolution',
    posterImage: '/posters/berlin.jpeg',
    status: 'upcoming',
    facebookGroupUrl: 'https://facebook.com/groups/iranberlin',
    telegramUrl: 'https://t.me/iranberlin',
  },
  {
    id: 'stockholm-jan-31',
    cityId: 'stockholm',
    title: 'Rally for Iran',
    description: 'Join Iranians in Stockholm at Norra Bantorget to protest the Islamic Republic. Speakers, chants, and solidarity. The Swedish-Iranian community stands united against tyranny.',
    date: '2026-01-31',
    startTime: '15:30',
    venue: 'Norra Bantorget',
    address: 'Norra Bantorget, Stockholm',
    coordinates: { lat: 59.3340, lng: 18.0583 },
    posterImage: '/posters/stockholm.jpeg',
    status: 'upcoming',
  },
  {
    id: 'vienna-feb-1',
    cityId: 'vienna',
    title: 'Solidarity with Iran',
    description: 'Gather at Heldenplatz to demand justice for those killed, imprisoned, and tortured by the regime. Vienna has a long history of Iranian activism—add your voice.',
    date: '2026-02-01',
    startTime: '12:00',
    endTime: '13:00',
    venue: 'Heldenplatz',
    address: 'Heldenplatz, 1010 Wien',
    coordinates: { lat: 48.2066, lng: 16.3633 },
    posterImage: '/posters/vienna-austria.jpg',
    status: 'upcoming',
  },
  {
    id: 'brussels-jan-31',
    cityId: 'brussels',
    title: 'Rally for Freedom in Iran',
    description: 'Protest at the heart of the EU. Demand European leaders take stronger action against the Iranian regime. Sanctions are not enough—show up and make noise.',
    date: '2026-01-31',
    startTime: '14:00',
    endTime: '16:00',
    venue: 'Av. Franklin Roosevelt 15',
    address: 'Av. Franklin Roosevelt 15, 1050 Ixelles',
    coordinates: { lat: 50.8137, lng: 4.3809 },
    posterImage: '/posters/brussels-jan-31.jpg',
    status: 'upcoming',
  },
  {
    id: 'brussels-feb-1',
    cityId: 'brussels',
    title: 'Rally for Freedom in Iran',
    description: 'Continued action in Brussels. The regime thinks we will tire. Prove them wrong. Every protest matters.',
    date: '2026-02-01',
    startTime: '14:00',
    endTime: '16:00',
    venue: 'Av. Franklin Roosevelt 15',
    address: 'Av. Franklin Roosevelt 15, 1050 Ixelles',
    coordinates: { lat: 50.8137, lng: 4.3809 },
    posterImage: '/posters/brussels-feb-1.jpeg',
    status: 'upcoming',
  },
  {
    id: 'munich-jan-30',
    cityId: 'munich',
    title: 'Rally for Iran',
    description: 'Evening protest in Munich. The Bavarian-Iranian community gathers at Gartnerplatz to remember the fallen and demand accountability for the regime\'s crimes.',
    date: '2026-01-30',
    startTime: '18:00',
    venue: 'Gartnerplatz',
    address: 'Gartnerplatz, 80469 Munchen',
    coordinates: { lat: 48.1306, lng: 11.5769 },
    posterImage: '/posters/munich-jan-30.jpeg',
    status: 'upcoming',
  },
  {
    id: 'munich-jan-31',
    cityId: 'munich',
    title: 'Rally for Iran',
    description: 'Back-to-back protests in Munich. Saturday afternoon rally with speakers and solidarity. The fight continues.',
    date: '2026-01-31',
    startTime: '16:00',
    venue: 'Gartnerplatz',
    address: 'Gartnerplatz, 80469 Munchen',
    coordinates: { lat: 48.1306, lng: 11.5769 },
    posterImage: '/posters/munich-jan-31.jpeg',
    status: 'upcoming',
  },
  {
    id: 'oslo-jan-31',
    cityId: 'oslo',
    title: 'March for Iran',
    description: 'March through central Oslo from Jernbanetorget to Eidsvolls Plass. Norwegians and Iranians unite against the Islamic Republic. Bring candles for those we\'ve lost.',
    date: '2026-01-31',
    startTime: '16:15',
    endTime: '18:00',
    venue: 'Jernbanetorget to Eidsvolls Plass',
    address: 'Jernbanetorget to Eidsvolls Plass, Oslo',
    coordinates: { lat: 59.9127, lng: 10.7518 },
    posterImage: '/posters/oslo.jpeg',
    status: 'upcoming',
  },
  {
    id: 'barcelona-jan-31',
    cityId: 'barcelona',
    title: 'Solidarity Rally for Iran',
    description: 'Placa de Catalunya becomes a stage for Iranian freedom. Spanish and Iranian activists stand together. The Mediterranean community will not be silent.',
    date: '2026-01-31',
    startTime: '17:00',
    venue: 'Placa de Catalunya',
    address: 'Placa de Catalunya, 08002 Barcelona',
    coordinates: { lat: 41.3870, lng: 2.1700 },
    posterImage: '/posters/barcelona.jpeg',
    status: 'upcoming',
  },
  {
    id: 'rome-jan-31',
    cityId: 'rome',
    title: 'Rally for Iran',
    description: 'Protest in Rome demanding Italy take stronger diplomatic action. The Iranian community in Italy has been fighting since day one. Join them.',
    date: '2026-01-31',
    startTime: '14:00',
    venue: 'Piazzale Ugo La Malfa',
    address: 'Piazzale Ugo La Malfa, Roma',
    coordinates: { lat: 41.9145, lng: 12.4723 },
    posterImage: '/posters/rome.png',
    status: 'upcoming',
  },
  {
    id: 'manchester-jan-31',
    cityId: 'manchester',
    title: 'Rally for Iran',
    description: 'Gather at Manchester Central Library. Northern England stands with Iran. Speeches, solidarity, and a clear message: the world is watching.',
    date: '2026-01-31',
    startTime: '12:00',
    endTime: '14:00',
    venue: 'Central Library',
    address: "St Peter's Square, Manchester M2 5PD",
    coordinates: { lat: 53.4784, lng: -2.2451 },
    posterImage: '/posters/manchester.jpeg',
    status: 'upcoming',
  },
  {
    id: 'sheffield-feb-1',
    cityId: 'sheffield',
    title: 'Solidarity Rally',
    description: 'Sheffield joins the global movement. Barker\'s Pool protest calling for freedom in Iran. Every city matters. Every voice counts.',
    date: '2026-02-01',
    startTime: '12:00',
    endTime: '14:00',
    venue: "Barker's Pool",
    address: "Barker's Pool, Sheffield S1 2JA",
    coordinates: { lat: 53.3814, lng: -1.4746 },
    posterImage: '/posters/sheffield.jpeg',
    status: 'upcoming',
  },
  {
    id: 'belfast-feb-1',
    cityId: 'belfast',
    title: 'Rally for Freedom',
    description: 'Belfast City Hall protest. Northern Ireland\'s Iranian community and allies demand action. From Belfast to Tehran, freedom will prevail.',
    date: '2026-02-01',
    startTime: '13:30',
    venue: 'Belfast City Hall',
    address: 'Donegall Square N, Belfast BT1 5GS',
    coordinates: { lat: 54.5964, lng: -5.9302 },
    posterImage: '/posters/belfast.jpeg',
    status: 'upcoming',
  },
  {
    id: 'cambridge-jan-31',
    cityId: 'cambridge',
    title: 'Rally for Iran',
    description: 'Cambridge Market Square rally. Students, academics, and the community unite. Knowledge without freedom is meaningless—stand with Iran.',
    date: '2026-01-31',
    startTime: '14:00',
    endTime: '16:00',
    venue: 'Market Square',
    address: 'Market Square, Cambridge',
    coordinates: { lat: 52.2054, lng: 0.1183 },
    posterImage: '/posters/cambridge.png',
    status: 'upcoming',
  },
  {
    id: 'frankfurt-jan-28',
    cityId: 'frankfurt',
    title: 'Rally for Iran (Wednesday)',
    description: 'Midweek protest in Frankfurt. The financial capital of Europe hears the cries of Iran. Rathenauplatz gathering—be there.',
    date: '2026-01-28',
    startTime: '17:00',
    venue: 'Rathenauplatz',
    address: 'Rathenauplatz (Goetheplatz), Frankfurt',
    coordinates: { lat: 50.1136, lng: 8.6743 },
    posterImage: '/posters/frankfurt-wednesday-and-saturday.jpeg',
    status: 'upcoming',
  },
  {
    id: 'frankfurt-jan-31',
    cityId: 'frankfurt',
    title: 'Rally for Iran (Saturday)',
    description: 'Saturday rally in Frankfurt. Larger crowds, louder voices. Germany\'s Iranian diaspora is one of the largest—make it count.',
    date: '2026-01-31',
    startTime: '15:00',
    venue: 'Rathenauplatz',
    address: 'Rathenauplatz (Goetheplatz), Frankfurt',
    coordinates: { lat: 50.1136, lng: 8.6743 },
    posterImage: '/posters/frankfurt.jpeg',
    status: 'upcoming',
  },
  {
    id: 'hamburg-jan-31',
    cityId: 'hamburg',
    title: 'Rally for Iran',
    description: 'Hamburg stands with Iran. Port city, global reach. Protest demanding international pressure on the regime.',
    date: '2026-01-31',
    startTime: '14:00',
    venue: 'Kurt-Schumacher-Allee 10',
    address: 'Kurt-Schumacher-Allee 10, Hamburg',
    coordinates: { lat: 53.5530, lng: 10.0065 },
    posterImage: '/posters/hamburg.jpeg',
    status: 'upcoming',
  },
  {
    id: 'hannover-jan-31',
    cityId: 'hannover',
    title: 'Rally for Iran',
    description: 'Protest at Neues Rathaus. Hannover\'s Iranian community has been tireless. Join them for a morning of solidarity and resistance.',
    date: '2026-01-31',
    startTime: '11:00',
    endTime: '14:00',
    venue: 'Neues Rathaus',
    address: 'Trammplatz 2, 30159 Hannover',
    coordinates: { lat: 52.3676, lng: 9.7385 },
    posterImage: '/posters/hannover.jpeg',
    status: 'upcoming',
  },
  {
    id: 'karlsruhe-jan-31',
    cityId: 'karlsruhe',
    title: 'March for Iran',
    description: 'March from Kronenplatz to Marktplatz. Karlsruhe takes to the streets. Every German city with Iranians is mobilizing.',
    date: '2026-01-31',
    startTime: '16:00',
    endTime: '18:00',
    venue: 'Kronenplatz to Marktplatz',
    address: 'Kronenplatz to Marktplatz, Karlsruhe',
    coordinates: { lat: 49.0094, lng: 8.4044 },
    posterImage: '/posters/karlsruhe-germany.jpeg',
    status: 'upcoming',
  },
  {
    id: 'stuttgart-jan-31',
    cityId: 'stuttgart',
    title: 'Rally for Iran',
    description: 'Three-hour protest in Stuttgart. Baden-Württemberg\'s capital joins the fight. Bring flags, bring energy, bring hope.',
    date: '2026-01-31',
    startTime: '14:00',
    endTime: '17:00',
    venue: 'Lautenschlagerstrasse',
    address: 'Lautenschlagerstrasse, 70173 Stuttgart',
    coordinates: { lat: 48.7831, lng: 9.1820 },
    posterImage: '/posters/stuttgart.jpeg',
    status: 'upcoming',
  },
  {
    id: 'grenoble-jan-31',
    cityId: 'grenoble',
    title: 'Rally for Iran',
    description: 'Grenoble\'s Place Victor Hugo becomes a voice for Iran. The French Alps echo with demands for freedom.',
    date: '2026-01-31',
    startTime: '14:00',
    venue: 'Place Victor Hugo',
    address: 'Place Victor Hugo, 38000 Grenoble',
    coordinates: { lat: 45.1875, lng: 5.7246 },
    posterImage: '/posters/grenoble-france.jpg',
    status: 'upcoming',
  },
  {
    id: 'gothenburg-jan-31',
    cityId: 'gothenburg',
    title: 'Rally for Iran',
    description: 'Gotaplatsen rally in Sweden\'s second city. Gothenburg\'s Iranian community won\'t rest until Iran is free.',
    date: '2026-01-31',
    startTime: '13:00',
    venue: 'Gotaplatsen',
    address: 'Gotaplatsen, Gothenburg',
    coordinates: { lat: 57.6969, lng: 11.9797 },
    posterImage: '/posters/gothenburg-sweden.jpeg',
    status: 'upcoming',
  },
  {
    id: 'stavanger-jan-31',
    cityId: 'stavanger',
    title: 'Rally for Iran',
    description: 'Torget protest in Stavanger. Norway\'s oil city demands accountability. The regime cannot hide from global pressure.',
    date: '2026-01-31',
    startTime: '12:00',
    endTime: '14:00',
    venue: 'Torget',
    address: 'Torget, Stavanger',
    coordinates: { lat: 58.9701, lng: 5.7305 },
    posterImage: '/posters/stavanger-norway.jpeg',
    status: 'upcoming',
  },
  {
    id: 'odense-jan-31',
    cityId: 'odense',
    title: 'Rally for Iran',
    description: 'Grabrødre Plads gathering in Odense. Denmark stands with Iran. One hour of solidarity that echoes across borders.',
    date: '2026-01-31',
    startTime: '13:00',
    endTime: '14:00',
    venue: 'Grabrødre Plads',
    address: 'Grabrødre Plads 1, 5000 Odense',
    coordinates: { lat: 55.3962, lng: 10.3872 },
    posterImage: '/posters/odense-denmark.jpg',
    status: 'upcoming',
  },
  {
    id: 'the-hague-jan-31',
    cityId: 'the-hague',
    title: 'Rally for Iran',
    description: 'Malieveld protest at the seat of international justice. The Hague knows war crimes when it sees them. Demand ICC action.',
    date: '2026-01-31',
    startTime: '14:00',
    endTime: '16:00',
    venue: 'Malieveld',
    address: 'Malieveld, Den Haag',
    coordinates: { lat: 52.0828, lng: 4.3245 },
    posterImage: '/posters/holland.jpeg',
    status: 'upcoming',
  },

  // North America Events
  {
    id: 'nyc-jan-31',
    cityId: 'new-york',
    title: 'Stand with the People of Iran',
    description: 'New York City rises for Iran. Protest on 5th Avenue demanding US action against the regime. The largest Iranian diaspora in America will not be silent.',
    date: '2026-01-31',
    startTime: '13:00',
    venue: '1033 5th Avenue',
    address: '1033 5th Avenue, NYC (Between 84th & 85th St)',
    coordinates: { lat: 40.7794, lng: -73.9632 },
    theme: 'Iranian Revolution',
    organizer: '@royal_army_nyc',
    posterImage: '/posters/nyc.jpeg',
    status: 'upcoming',
    facebookGroupUrl: 'https://facebook.com/groups/irannyc',
    instagramUrl: 'https://instagram.com/royal_army_nyc',
  },
  {
    id: 'sf-jan-31',
    cityId: 'san-francisco',
    title: 'Rally for Iran',
    description: 'Golden Gate Bridge protest. Silicon Valley\'s Iranian tech community and allies gather. Visibility matters—be seen, be heard.',
    date: '2026-01-31',
    startTime: '11:00',
    endTime: '14:00',
    venue: 'Golden Gate Bridge Gift Center',
    address: 'Golden Gate Bridge Gift Center, San Francisco, CA',
    coordinates: { lat: 37.8079, lng: -122.4750 },
    posterImage: '/posters/san-francisco.jpeg',
    status: 'upcoming',
  },
  {
    id: 'westwood-feb-1',
    cityId: 'los-angeles',
    title: 'Rally for Iran',
    description: 'Persian Square in Westwood—the heart of Iranian Los Angeles. The largest Iranian population outside Iran demands change. This is where it matters most.',
    date: '2026-02-01',
    startTime: '13:00',
    endTime: '15:00',
    venue: 'Persian Square',
    address: 'Westwood Blvd, Los Angeles, CA 90024',
    coordinates: { lat: 34.0611, lng: -118.4466 },
    posterImage: '/posters/westwood-la.jpeg',
    status: 'upcoming',
  },
  {
    id: 'irvine-jan-31',
    cityId: 'irvine',
    title: 'Rally for Iran',
    description: 'Orange County protest. Irvine\'s Iranian community takes to the streets. Southern California stands united.',
    date: '2026-01-31',
    startTime: '14:00',
    endTime: '16:00',
    venue: 'Culver & Barranca Pkwy',
    address: 'Culver & Barranca Pkwy, Irvine, CA',
    coordinates: { lat: 33.6897, lng: -117.8270 },
    posterImage: '/posters/irvine-ca.png',
    status: 'upcoming',
  },
  {
    id: 'irvine-feb-1',
    cityId: 'irvine',
    title: 'Rally for Iran',
    description: 'Back-to-back protests in Irvine. Sunday rally continues the pressure. The regime must know we won\'t stop.',
    date: '2026-02-01',
    startTime: '14:00',
    endTime: '16:00',
    venue: 'Culver & Barranca Pkwy',
    address: 'Culver & Barranca Pkwy, Irvine, CA',
    coordinates: { lat: 33.6897, lng: -117.8270 },
    posterImage: '/posters/irvine-ca.png',
    status: 'upcoming',
  },
  {
    id: 'houston-jan-30',
    cityId: 'houston',
    title: 'Rally for Iran (Friday)',
    description: 'Friday protest on Westheimer. Texas Iranians mobilize. The energy capital of America demands freedom for Iran.',
    date: '2026-01-30',
    startTime: '16:00',
    venue: 'Westheimer',
    address: 'Westheimer, Houston, TX',
    coordinates: { lat: 29.7450, lng: -95.4620 },
    posterImage: '/posters/houston-friday.jpeg',
    status: 'upcoming',
  },
  {
    id: 'houston-feb-1',
    cityId: 'houston',
    title: 'Rally for Iran (Sunday)',
    description: 'Hermann Park Sunday rally. Houston\'s second protest of the weekend. Consistent pressure creates change.',
    date: '2026-02-01',
    startTime: '15:00',
    venue: 'Hermann Park',
    address: '6001 Fannin St, Houston, TX 77030',
    coordinates: { lat: 29.7138, lng: -95.3911 },
    posterImage: '/posters/houston-sunday.jpg',
    status: 'upcoming',
  },
  {
    id: 'dallas-jan-31',
    cityId: 'dallas',
    title: 'Rally for Iran',
    description: 'Dallas-Fort Worth area protest in Plano. North Texas Iranians demand action. Every voice amplifies the message.',
    date: '2026-01-31',
    startTime: '15:00',
    endTime: '17:30',
    venue: '9700 Coit Rd',
    address: '9700 Coit Rd, Plano, TX',
    coordinates: { lat: 33.0356, lng: -96.7698 },
    posterImage: '/posters/dallas-plano-texas.jpeg',
    status: 'upcoming',
  },
  {
    id: 'san-antonio-feb-1',
    cityId: 'san-antonio',
    title: 'Rally for Iran',
    description: 'San Antonio joins the movement. South Texas stands with Iran. From the Alamo city, a message of resistance.',
    date: '2026-02-01',
    startTime: '13:00',
    endTime: '15:00',
    venue: '4335 NW Loop 410',
    address: '4335 NW Loop 410, San Antonio, TX',
    coordinates: { lat: 29.5072, lng: -98.5677 },
    posterImage: '/posters/san-antonio-texas.jpeg',
    status: 'upcoming',
  },
  {
    id: 'nashville-jan-31',
    cityId: 'nashville',
    title: 'Rally for Iran',
    description: 'Federal building protest in Nashville. Tennessee\'s Iranian community makes their presence known. The South remembers Iran.',
    date: '2026-01-31',
    startTime: '14:00',
    endTime: '15:00',
    venue: 'Estes Federal Building',
    address: '801 Broadway, Nashville, TN',
    coordinates: { lat: 36.1588, lng: -86.7787 },
    posterImage: '/posters/nashville-tn.jpeg',
    status: 'upcoming',
  },
  {
    id: 'wichita-jan-31',
    cityId: 'wichita',
    title: 'Rally for Iran',
    description: 'Keeper of the Plains gathering. Kansas stands with Iran. Heartland solidarity—middle America cares.',
    date: '2026-01-31',
    startTime: '11:00',
    venue: 'Keeper Of The Plains',
    address: '339 Veterans Pkwy, Wichita, KS',
    coordinates: { lat: 37.6840, lng: -97.3516 },
    posterImage: '/posters/wichita-kansas.jpeg',
    status: 'upcoming',
  },
  {
    id: 'hartford-jan-31',
    cityId: 'hartford',
    title: 'Rally for Iran',
    description: 'State Capitol protest in Hartford. Connecticut demands federal action. New England\'s voice for Iran.',
    date: '2026-01-31',
    startTime: '13:00',
    endTime: '15:00',
    venue: 'State Capitol',
    address: '210 Capitol Ave, Hartford, CT',
    coordinates: { lat: 41.7642, lng: -72.6826 },
    posterImage: '/posters/hartford-connecticut.jpeg',
    status: 'upcoming',
  },
  {
    id: 'tempe-jan-30',
    cityId: 'tempe',
    title: 'Rally for Iran',
    description: 'Arizona State University area protest. Desert heat, burning passion for freedom. Phoenix metro mobilizes.',
    date: '2026-01-30',
    startTime: '16:00',
    endTime: '18:00',
    venue: '452 E University Dr',
    address: '452 E University Dr, Tempe, AZ',
    coordinates: { lat: 33.4217, lng: -111.9341 },
    posterImage: '/posters/tempe-arizona.jpg',
    status: 'upcoming',
  },
  {
    id: 'orlando-feb-1',
    cityId: 'orlando',
    title: 'Rally for Iran',
    description: 'Lake Eola Park protest. Central Florida stands with Iran. From the theme park capital, a serious message.',
    date: '2026-02-01',
    startTime: '12:00',
    endTime: '14:00',
    venue: 'Lake Eola',
    address: 'Lake Eola Park, Orlando, FL',
    coordinates: { lat: 28.5433, lng: -81.3736 },
    posterImage: '/posters/orlando.jpeg',
    status: 'upcoming',
  },
  {
    id: 'great-neck-feb-1',
    cityId: 'great-neck',
    title: 'Rally for Iran',
    description: 'Long Island\'s Persian Jewish community gathers at Village Green Park. Great Neck has one of the largest Iranian Jewish populations in America.',
    date: '2026-02-01',
    startTime: '12:30',
    venue: 'Village Green Park',
    address: 'Village Green Park, Great Neck, NY',
    coordinates: { lat: 40.8007, lng: -73.7285 },
    posterImage: '/posters/village-green-park-great-neck.jpeg',
    status: 'upcoming',
  },
  {
    id: 'bellevue-jan-30',
    cityId: 'bellevue',
    title: 'Rally for Iran',
    description: 'Pacific Northwest protest in Bellevue. Seattle area\'s Iranian tech workers and families unite. Washington State cares.',
    date: '2026-01-30',
    startTime: '13:00',
    venue: 'Bellevue Park',
    address: 'Bellevue Park, Bellevue, WA',
    coordinates: { lat: 47.6137, lng: -122.2067 },
    posterImage: '/posters/washington-state.jpeg',
    status: 'upcoming',
  },
  {
    id: 'toronto-feb-1',
    cityId: 'toronto',
    title: 'Rally for Iran',
    description: 'Canada\'s largest city rises for Iran. Dundas Square protest—thousands expected. Toronto\'s massive Iranian community leads the charge.',
    date: '2026-02-01',
    startTime: '13:00',
    venue: 'Sankofa (Dundas) Square',
    address: 'Sankofa Square, Dundas & Yonge, Toronto',
    coordinates: { lat: 43.6561, lng: -79.3802 },
    posterImage: '/posters/toronto.jpeg',
    status: 'upcoming',
    facebookGroupUrl: 'https://facebook.com/groups/irantoronto',
    telegramUrl: 'https://t.me/irantoronto',
  },
  {
    id: 'montreal-jan-31',
    cityId: 'montreal',
    title: 'Rally for Iran',
    description: 'Atwater Metro area protest. Montreal\'s Iranian community—students, families, professionals—demand action from Canada.',
    date: '2026-01-31',
    startTime: '14:00',
    endTime: '16:00',
    venue: 'Atwater Metro',
    address: 'Atwater Metro area, Montreal, QC',
    coordinates: { lat: 45.4897, lng: -73.5857 },
    posterImage: '/posters/montreal-english.jpg',
    status: 'upcoming',
  },
  {
    id: 'ottawa-jan-30',
    cityId: 'ottawa',
    title: 'Rally for Iran (Friday)',
    description: 'University of Ottawa protest. Students and faculty demand the Canadian government do more. Academic solidarity.',
    date: '2026-01-30',
    startTime: '11:30',
    venue: 'Tabaret Hall',
    address: 'Tabaret Hall, University of Ottawa',
    coordinates: { lat: 45.4231, lng: -75.6830 },
    posterImage: '/posters/ottawa-friday.jpeg',
    status: 'upcoming',
  },
  {
    id: 'ottawa-feb-1',
    cityId: 'ottawa',
    title: 'Rally for Iran (Sunday)',
    description: 'Parliament Hill protest. Canada\'s seat of power hears the cry for Iran. Demand sanctions, demand action, demand justice.',
    date: '2026-02-01',
    startTime: '12:00',
    venue: 'Parliament Hill',
    address: 'Wellington St, Ottawa, ON',
    coordinates: { lat: 45.4236, lng: -75.7009 },
    posterImage: '/posters/ottawa-feb-1.jpeg',
    status: 'upcoming',
  },
  {
    id: 'prince-george-feb-7',
    cityId: 'prince-george',
    title: 'Rally for Iran',
    description: 'Northern BC stands with Iran. Prince George\'s small but mighty Iranian community gathers. Every city counts.',
    date: '2026-02-07',
    startTime: '18:00',
    endTime: '20:00',
    venue: 'St. Michael Hall',
    address: 'St. Michael Hall, Prince George, BC',
    coordinates: { lat: 53.9171, lng: -122.7497 },
    posterImage: '/posters/prince-george-bc.jpeg',
    status: 'upcoming',
  },
  {
    id: 'charlottetown-feb-1',
    cityId: 'charlottetown',
    title: 'Rally for Iran',
    description: 'Prince Edward Island protest at the Cenotaph. Canada\'s smallest province, biggest heart. Maritime solidarity.',
    date: '2026-02-01',
    startTime: '11:30',
    endTime: '13:00',
    venue: 'Cenotaph of Veterans',
    address: 'Cenotaph of Veterans, Charlottetown, PEI',
    coordinates: { lat: 46.2343, lng: -63.1268 },
    posterImage: '/posters/charlottetown-pei.jpeg',
    status: 'upcoming',
  },

  // Oceania Events
  {
    id: 'sydney-feb-1',
    cityId: 'sydney',
    title: 'Rally for Iran',
    description: 'Hyde Park protest in Sydney. Australia\'s largest city stands with Iran. The Southern Hemisphere joins the global movement.',
    date: '2026-02-01',
    startTime: '17:00',
    endTime: '19:00',
    venue: 'Hyde Park North',
    address: 'Hyde Park North, Sydney NSW 2000',
    coordinates: { lat: -33.8723, lng: 151.2109 },
    posterImage: '/posters/sydney.jpeg',
    status: 'upcoming',
  },
  {
    id: 'brisbane-jan-31',
    cityId: 'brisbane',
    title: 'Rally for Iran',
    description: 'Queensland stands with Iran. Reddacliff Place protest in Brisbane CBD. Australia\'s sunshine state brings light to the cause.',
    date: '2026-01-31',
    startTime: '16:00',
    endTime: '18:00',
    venue: 'Reddacliff Place',
    address: 'Reddacliff Place, Brisbane QLD 4000',
    coordinates: { lat: -27.4697, lng: 153.0247 },
    posterImage: '/posters/brisbane.jpeg',
    status: 'upcoming',
  },
  {
    id: 'auckland-jan-31',
    cityId: 'auckland',
    title: 'Rally for Iran',
    description: 'New Zealand rises for Iran. Western Park gathering in Auckland. From the bottom of the world, solidarity reaches Tehran.',
    date: '2026-01-31',
    startTime: '18:00',
    endTime: '19:00',
    venue: 'Western Park',
    address: 'Western Park, Ponsonby, Auckland',
    coordinates: { lat: -36.8587, lng: 174.7449 },
    posterImage: '/posters/auckland-nz.jpeg',
    status: 'upcoming',
  },
]

export function getEventById(id: string): RallyEvent | undefined {
  return events.find((event) => event.id === id)
}

export function getEventsByCityId(cityId: string): RallyEvent[] {
  return events.filter((event) => event.cityId === cityId)
}

export function getUpcomingEvents(): RallyEvent[] {
  const now = new Date()
  return events
    .filter((event) => new Date(event.date) >= now)
    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime())
}
