import type { Coordinates, EventStatus } from '@/types'

export interface RallyEvent {
  id: string
  cityId: string
  title: string
  date: string
  startTime: string
  endTime?: string
  venue: string
  address: string
  coordinates: Coordinates
  theme?: string
  organizer?: string
  posterImage: string
  status: EventStatus
  eventUrl?: string
  facebookGroupUrl?: string
  rsvpUrl?: string
  instagramUrl?: string
  telegramUrl?: string
}

export const events: RallyEvent[] = [
  // Europe Events
  {
    id: 'berlin-jan-31',
    cityId: 'berlin',
    title: 'Stand with the People of Iran',
    date: '2026-01-31',
    startTime: '14:00',
    endTime: '18:00',
    venue: 'Kurfurstendamm / Joachimstaler Str.',
    address: 'Kurfurstendamm / Joachimstaler Str., Berlin',
    coordinates: { lat: 52.5046, lng: 13.3326 },
    theme: 'Iranian Revolution',
    posterImage: '/posters/Berlin.jpeg',
    status: 'upcoming',
    facebookGroupUrl: 'https://facebook.com/groups/iranberlin',
    telegramUrl: 'https://t.me/iranberlin',
  },
  {
    id: 'stockholm-jan-31',
    cityId: 'stockholm',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '15:30',
    venue: 'Norra Bantorget',
    address: 'Norra Bantorget, Stockholm',
    coordinates: { lat: 59.3340, lng: 18.0583 },
    posterImage: '/posters/Stockholm.jpeg',
    status: 'upcoming',
  },
  {
    id: 'vienna-feb-1',
    cityId: 'vienna',
    title: 'Solidarity with Iran',
    date: '2026-02-01',
    startTime: '12:00',
    endTime: '13:00',
    venue: 'Heldenplatz',
    address: 'Heldenplatz, 1010 Wien',
    coordinates: { lat: 48.2066, lng: 16.3633 },
    posterImage: '/posters/Vienna, Austria.jpg',
    status: 'upcoming',
  },
  {
    id: 'brussels-jan-31',
    cityId: 'brussels',
    title: 'Rally for Freedom in Iran',
    date: '2026-01-31',
    startTime: '14:00',
    endTime: '16:00',
    venue: 'Av. Franklin Roosevelt 15',
    address: 'Av. Franklin Roosevelt 15, 1050 Ixelles',
    coordinates: { lat: 50.8137, lng: 4.3809 },
    posterImage: '/posters/Brussels - Jan 31.jpg',
    status: 'upcoming',
  },
  {
    id: 'brussels-feb-1',
    cityId: 'brussels',
    title: 'Rally for Freedom in Iran',
    date: '2026-02-01',
    startTime: '14:00',
    endTime: '16:00',
    venue: 'Av. Franklin Roosevelt 15',
    address: 'Av. Franklin Roosevelt 15, 1050 Ixelles',
    coordinates: { lat: 50.8137, lng: 4.3809 },
    posterImage: '/posters/Brussels - Feb 1.jpeg',
    status: 'upcoming',
  },
  {
    id: 'munich-jan-30',
    cityId: 'munich',
    title: 'Rally for Iran',
    date: '2026-01-30',
    startTime: '18:00',
    venue: 'Gartnerplatz',
    address: 'Gartnerplatz, 80469 Munchen',
    coordinates: { lat: 48.1306, lng: 11.5769 },
    posterImage: '/posters/Munich Jan 30.jpeg',
    status: 'upcoming',
  },
  {
    id: 'munich-jan-31',
    cityId: 'munich',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '16:00',
    venue: 'Gartnerplatz',
    address: 'Gartnerplatz, 80469 Munchen',
    coordinates: { lat: 48.1306, lng: 11.5769 },
    posterImage: '/posters/Munich Jan 31.jpeg',
    status: 'upcoming',
  },
  {
    id: 'oslo-jan-31',
    cityId: 'oslo',
    title: 'March for Iran',
    date: '2026-01-31',
    startTime: '16:15',
    endTime: '18:00',
    venue: 'Jernbanetorget to Eidsvolls Plass',
    address: 'Jernbanetorget to Eidsvolls Plass, Oslo',
    coordinates: { lat: 59.9127, lng: 10.7518 },
    posterImage: '/posters/Oslo.jpeg',
    status: 'upcoming',
  },
  {
    id: 'barcelona-jan-31',
    cityId: 'barcelona',
    title: 'Solidarity Rally for Iran',
    date: '2026-01-31',
    startTime: '17:00',
    venue: 'Placa de Catalunya',
    address: 'Placa de Catalunya, 08002 Barcelona',
    coordinates: { lat: 41.3870, lng: 2.1700 },
    posterImage: '/posters/Barcelona.jpeg',
    status: 'upcoming',
  },
  {
    id: 'rome-jan-31',
    cityId: 'rome',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '14:00',
    venue: 'Piazzale Ugo La Malfa',
    address: 'Piazzale Ugo La Malfa, Roma',
    coordinates: { lat: 41.9145, lng: 12.4723 },
    posterImage: '/posters/Rome.png',
    status: 'upcoming',
  },
  {
    id: 'manchester-jan-31',
    cityId: 'manchester',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '12:00',
    endTime: '14:00',
    venue: 'Central Library',
    address: "St Peter's Square, Manchester M2 5PD",
    coordinates: { lat: 53.4784, lng: -2.2451 },
    posterImage: '/posters/Manchester.jpeg',
    status: 'upcoming',
  },
  {
    id: 'sheffield-feb-1',
    cityId: 'sheffield',
    title: 'Solidarity Rally',
    date: '2026-02-01',
    startTime: '12:00',
    endTime: '14:00',
    venue: "Barker's Pool",
    address: "Barker's Pool, Sheffield S1 2JA",
    coordinates: { lat: 53.3814, lng: -1.4746 },
    posterImage: '/posters/Sheffield.jpeg',
    status: 'upcoming',
  },
  {
    id: 'belfast-feb-1',
    cityId: 'belfast',
    title: 'Rally for Freedom',
    date: '2026-02-01',
    startTime: '13:30',
    venue: 'Belfast City Hall',
    address: 'Donegall Square N, Belfast BT1 5GS',
    coordinates: { lat: 54.5964, lng: -5.9302 },
    posterImage: '/posters/Belfast.jpeg',
    status: 'upcoming',
  },
  {
    id: 'cambridge-jan-31',
    cityId: 'cambridge',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '14:00',
    endTime: '16:00',
    venue: 'Market Square',
    address: 'Market Square, Cambridge',
    coordinates: { lat: 52.2054, lng: 0.1183 },
    posterImage: '/posters/Cambridge.png',
    status: 'upcoming',
  },
  {
    id: 'frankfurt-jan-28',
    cityId: 'frankfurt',
    title: 'Rally for Iran (Wednesday)',
    date: '2026-01-28',
    startTime: '17:00',
    venue: 'Rathenauplatz',
    address: 'Rathenauplatz (Goetheplatz), Frankfurt',
    coordinates: { lat: 50.1136, lng: 8.6743 },
    posterImage: '/posters/Frankfurt - WEDNESDAY and SATURDAY.jpeg',
    status: 'upcoming',
  },
  {
    id: 'frankfurt-jan-31',
    cityId: 'frankfurt',
    title: 'Rally for Iran (Saturday)',
    date: '2026-01-31',
    startTime: '15:00',
    venue: 'Rathenauplatz',
    address: 'Rathenauplatz (Goetheplatz), Frankfurt',
    coordinates: { lat: 50.1136, lng: 8.6743 },
    posterImage: '/posters/Frankfurt.jpeg',
    status: 'upcoming',
  },
  {
    id: 'hamburg-jan-31',
    cityId: 'hamburg',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '14:00',
    venue: 'Kurt-Schumacher-Allee 10',
    address: 'Kurt-Schumacher-Allee 10, Hamburg',
    coordinates: { lat: 53.5530, lng: 10.0065 },
    posterImage: '/posters/Hamburg.jpeg',
    status: 'upcoming',
  },
  {
    id: 'hannover-jan-31',
    cityId: 'hannover',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '11:00',
    endTime: '14:00',
    venue: 'Neues Rathaus',
    address: 'Trammplatz 2, 30159 Hannover',
    coordinates: { lat: 52.3676, lng: 9.7385 },
    posterImage: '/posters/Hannover.jpeg',
    status: 'upcoming',
  },
  {
    id: 'karlsruhe-jan-31',
    cityId: 'karlsruhe',
    title: 'March for Iran',
    date: '2026-01-31',
    startTime: '16:00',
    endTime: '18:00',
    venue: 'Kronenplatz to Marktplatz',
    address: 'Kronenplatz to Marktplatz, Karlsruhe',
    coordinates: { lat: 49.0094, lng: 8.4044 },
    posterImage: '/posters/Karlsruhe, Germany.jpeg',
    status: 'upcoming',
  },
  {
    id: 'stuttgart-jan-31',
    cityId: 'stuttgart',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '14:00',
    endTime: '17:00',
    venue: 'Lautenschlagerstrasse',
    address: 'Lautenschlagerstrasse, 70173 Stuttgart',
    coordinates: { lat: 48.7831, lng: 9.1820 },
    posterImage: '/posters/Stuttgart.jpeg',
    status: 'upcoming',
  },
  {
    id: 'grenoble-jan-31',
    cityId: 'grenoble',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '14:00',
    venue: 'Place Victor Hugo',
    address: 'Place Victor Hugo, 38000 Grenoble',
    coordinates: { lat: 45.1875, lng: 5.7246 },
    posterImage: '/posters/Grenoble, France.jpg',
    status: 'upcoming',
  },
  {
    id: 'gothenburg-jan-31',
    cityId: 'gothenburg',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '13:00',
    venue: 'Gotaplatsen',
    address: 'Gotaplatsen, Gothenburg',
    coordinates: { lat: 57.6969, lng: 11.9797 },
    posterImage: '/posters/Gothenburg, Sweden.jpeg',
    status: 'upcoming',
  },
  {
    id: 'stavanger-jan-31',
    cityId: 'stavanger',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '12:00',
    endTime: '14:00',
    venue: 'Torget',
    address: 'Torget, Stavanger',
    coordinates: { lat: 58.9701, lng: 5.7305 },
    posterImage: '/posters/Stavanger, Norway.jpeg',
    status: 'upcoming',
  },
  {
    id: 'odense-jan-31',
    cityId: 'odense',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '13:00',
    endTime: '14:00',
    venue: 'Grabrødre Plads',
    address: 'Grabrødre Plads 1, 5000 Odense',
    coordinates: { lat: 55.3962, lng: 10.3872 },
    posterImage: '/posters/Odense, Denmark.jpg',
    status: 'upcoming',
  },
  {
    id: 'the-hague-jan-31',
    cityId: 'the-hague',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '14:00',
    endTime: '16:00',
    venue: 'Malieveld',
    address: 'Malieveld, Den Haag',
    coordinates: { lat: 52.0828, lng: 4.3245 },
    posterImage: '/posters/Holland.jpeg',
    status: 'upcoming',
  },

  // North America Events
  {
    id: 'nyc-jan-31',
    cityId: 'new-york',
    title: 'Stand with the People of Iran',
    date: '2026-01-31',
    startTime: '13:00',
    venue: '1033 5th Avenue',
    address: '1033 5th Avenue, NYC (Between 84th & 85th St)',
    coordinates: { lat: 40.7794, lng: -73.9632 },
    theme: 'Iranian Revolution',
    organizer: '@royal_army_nyc',
    posterImage: '/posters/NYC.jpeg',
    status: 'upcoming',
    facebookGroupUrl: 'https://facebook.com/groups/irannyc',
    instagramUrl: 'https://instagram.com/royal_army_nyc',
  },
  {
    id: 'sf-jan-31',
    cityId: 'san-francisco',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '11:00',
    endTime: '14:00',
    venue: 'Golden Gate Bridge Gift Center',
    address: 'Golden Gate Bridge Gift Center, San Francisco, CA',
    coordinates: { lat: 37.8079, lng: -122.4750 },
    posterImage: '/posters/San Francisco.jpeg',
    status: 'upcoming',
  },
  {
    id: 'westwood-feb-1',
    cityId: 'los-angeles',
    title: 'Rally for Iran',
    date: '2026-02-01',
    startTime: '13:00',
    endTime: '15:00',
    venue: 'Persian Square',
    address: 'Westwood Blvd, Los Angeles, CA 90024',
    coordinates: { lat: 34.0611, lng: -118.4466 },
    posterImage: '/posters/Westwood LA.jpeg',
    status: 'upcoming',
  },
  {
    id: 'irvine-jan-31',
    cityId: 'irvine',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '14:00',
    endTime: '16:00',
    venue: 'Culver & Barranca Pkwy',
    address: 'Culver & Barranca Pkwy, Irvine, CA',
    coordinates: { lat: 33.6897, lng: -117.8270 },
    posterImage: '/posters/Irvine, CA.png',
    status: 'upcoming',
  },
  {
    id: 'irvine-feb-1',
    cityId: 'irvine',
    title: 'Rally for Iran',
    date: '2026-02-01',
    startTime: '14:00',
    endTime: '16:00',
    venue: 'Culver & Barranca Pkwy',
    address: 'Culver & Barranca Pkwy, Irvine, CA',
    coordinates: { lat: 33.6897, lng: -117.8270 },
    posterImage: '/posters/Irvine, CA.png',
    status: 'upcoming',
  },
  {
    id: 'houston-jan-30',
    cityId: 'houston',
    title: 'Rally for Iran (Friday)',
    date: '2026-01-30',
    startTime: '16:00',
    venue: 'Westheimer',
    address: 'Westheimer, Houston, TX',
    coordinates: { lat: 29.7450, lng: -95.4620 },
    posterImage: '/posters/Houston - Friday.jpeg',
    status: 'upcoming',
  },
  {
    id: 'houston-feb-1',
    cityId: 'houston',
    title: 'Rally for Iran (Sunday)',
    date: '2026-02-01',
    startTime: '15:00',
    venue: 'Hermann Park',
    address: '6001 Fannin St, Houston, TX 77030',
    coordinates: { lat: 29.7138, lng: -95.3911 },
    posterImage: '/posters/Houston - Sunday.jpg',
    status: 'upcoming',
  },
  {
    id: 'dallas-jan-31',
    cityId: 'dallas',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '15:00',
    endTime: '17:30',
    venue: '9700 Coit Rd',
    address: '9700 Coit Rd, Plano, TX',
    coordinates: { lat: 33.0356, lng: -96.7698 },
    posterImage: '/posters/Dallas (Plano), Texas.jpeg',
    status: 'upcoming',
  },
  {
    id: 'san-antonio-feb-1',
    cityId: 'san-antonio',
    title: 'Rally for Iran',
    date: '2026-02-01',
    startTime: '13:00',
    endTime: '15:00',
    venue: '4335 NW Loop 410',
    address: '4335 NW Loop 410, San Antonio, TX',
    coordinates: { lat: 29.5072, lng: -98.5677 },
    posterImage: '/posters/San Antonio, Texas.jpeg',
    status: 'upcoming',
  },
  {
    id: 'nashville-jan-31',
    cityId: 'nashville',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '14:00',
    endTime: '15:00',
    venue: 'Estes Federal Building',
    address: '801 Broadway, Nashville, TN',
    coordinates: { lat: 36.1588, lng: -86.7787 },
    posterImage: '/posters/Nashville, TN.jpeg',
    status: 'upcoming',
  },
  {
    id: 'wichita-jan-31',
    cityId: 'wichita',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '11:00',
    venue: 'Keeper Of The Plains',
    address: '339 Veterans Pkwy, Wichita, KS',
    coordinates: { lat: 37.6840, lng: -97.3516 },
    posterImage: '/posters/Wichita, Kansas.jpeg',
    status: 'upcoming',
  },
  {
    id: 'hartford-jan-31',
    cityId: 'hartford',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '13:00',
    endTime: '15:00',
    venue: 'State Capitol',
    address: '210 Capitol Ave, Hartford, CT',
    coordinates: { lat: 41.7642, lng: -72.6826 },
    posterImage: '/posters/Hartford, Connecticut.jpeg',
    status: 'upcoming',
  },
  {
    id: 'tempe-jan-30',
    cityId: 'tempe',
    title: 'Rally for Iran',
    date: '2026-01-30',
    startTime: '16:00',
    endTime: '18:00',
    venue: '452 E University Dr',
    address: '452 E University Dr, Tempe, AZ',
    coordinates: { lat: 33.4217, lng: -111.9341 },
    posterImage: '/posters/Tempe, Arizona.jpg',
    status: 'upcoming',
  },
  {
    id: 'orlando-feb-1',
    cityId: 'orlando',
    title: 'Rally for Iran',
    date: '2026-02-01',
    startTime: '12:00',
    endTime: '14:00',
    venue: 'Lake Eola',
    address: 'Lake Eola Park, Orlando, FL',
    coordinates: { lat: 28.5433, lng: -81.3736 },
    posterImage: '/posters/Orlando.jpeg',
    status: 'upcoming',
  },
  {
    id: 'great-neck-feb-1',
    cityId: 'great-neck',
    title: 'Rally for Iran',
    date: '2026-02-01',
    startTime: '12:30',
    venue: 'Village Green Park',
    address: 'Village Green Park, Great Neck, NY',
    coordinates: { lat: 40.8007, lng: -73.7285 },
    posterImage: '/posters/Village Green Park, Great Neck.jpeg',
    status: 'upcoming',
  },
  {
    id: 'bellevue-jan-30',
    cityId: 'bellevue',
    title: 'Rally for Iran',
    date: '2026-01-30',
    startTime: '13:00',
    venue: 'Bellevue Park',
    address: 'Bellevue Park, Bellevue, WA',
    coordinates: { lat: 47.6137, lng: -122.2067 },
    posterImage: '/posters/Washington State.jpeg',
    status: 'upcoming',
  },
  {
    id: 'toronto-feb-1',
    cityId: 'toronto',
    title: 'Rally for Iran',
    date: '2026-02-01',
    startTime: '13:00',
    venue: 'Sankofa (Dundas) Square',
    address: 'Sankofa Square, Dundas & Yonge, Toronto',
    coordinates: { lat: 43.6561, lng: -79.3802 },
    posterImage: '/posters/Toronto.jpeg',
    status: 'upcoming',
    facebookGroupUrl: 'https://facebook.com/groups/irantoronto',
    telegramUrl: 'https://t.me/irantoronto',
  },
  {
    id: 'montreal-jan-31',
    cityId: 'montreal',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '14:00',
    endTime: '16:00',
    venue: 'Atwater Metro',
    address: 'Atwater Metro area, Montreal, QC',
    coordinates: { lat: 45.4897, lng: -73.5857 },
    posterImage: '/posters/Montreal English.jpg',
    status: 'upcoming',
  },
  {
    id: 'ottawa-jan-30',
    cityId: 'ottawa',
    title: 'Rally for Iran (Friday)',
    date: '2026-01-30',
    startTime: '11:30',
    venue: 'Tabaret Hall',
    address: 'Tabaret Hall, University of Ottawa',
    coordinates: { lat: 45.4231, lng: -75.6830 },
    posterImage: '/posters/Ottawa - Friday.jpeg',
    status: 'upcoming',
  },
  {
    id: 'ottawa-feb-1',
    cityId: 'ottawa',
    title: 'Rally for Iran (Sunday)',
    date: '2026-02-01',
    startTime: '12:00',
    venue: 'Parliament Hill',
    address: 'Wellington St, Ottawa, ON',
    coordinates: { lat: 45.4236, lng: -75.7009 },
    posterImage: '/posters/Ottawa - Feb 1.jpeg',
    status: 'upcoming',
  },
  {
    id: 'prince-george-feb-7',
    cityId: 'prince-george',
    title: 'Rally for Iran',
    date: '2026-02-07',
    startTime: '18:00',
    endTime: '20:00',
    venue: 'St. Michael Hall',
    address: 'St. Michael Hall, Prince George, BC',
    coordinates: { lat: 53.9171, lng: -122.7497 },
    posterImage: '/posters/Prince George, BC.jpeg',
    status: 'upcoming',
  },
  {
    id: 'charlottetown-feb-1',
    cityId: 'charlottetown',
    title: 'Rally for Iran',
    date: '2026-02-01',
    startTime: '11:30',
    endTime: '13:00',
    venue: 'Cenotaph of Veterans',
    address: 'Cenotaph of Veterans, Charlottetown, PEI',
    coordinates: { lat: 46.2343, lng: -63.1268 },
    posterImage: '/posters/Charlottetown, PEI.jpeg',
    status: 'upcoming',
  },

  // Oceania Events
  {
    id: 'sydney-feb-1',
    cityId: 'sydney',
    title: 'Rally for Iran',
    date: '2026-02-01',
    startTime: '17:00',
    endTime: '19:00',
    venue: 'Hyde Park North',
    address: 'Hyde Park North, Sydney NSW 2000',
    coordinates: { lat: -33.8723, lng: 151.2109 },
    posterImage: '/posters/Sydney.jpeg',
    status: 'upcoming',
  },
  {
    id: 'brisbane-jan-31',
    cityId: 'brisbane',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '16:00',
    endTime: '18:00',
    venue: 'Reddacliff Place',
    address: 'Reddacliff Place, Brisbane QLD 4000',
    coordinates: { lat: -27.4697, lng: 153.0247 },
    posterImage: '/posters/Brisbane.jpeg',
    status: 'upcoming',
  },
  {
    id: 'auckland-jan-31',
    cityId: 'auckland',
    title: 'Rally for Iran',
    date: '2026-01-31',
    startTime: '18:00',
    endTime: '19:00',
    venue: 'Western Park',
    address: 'Western Park, Ponsonby, Auckland',
    coordinates: { lat: -36.8587, lng: 174.7449 },
    posterImage: '/posters/Auckland, NZ.jpeg',
    status: 'upcoming',
  },
]

export function getEventById(id: string): RallyEvent | undefined {
  return events.find((event) => event.id === id)
}

export function getEventsByCityId(cityId: string): RallyEvent[] {
  return events.filter((event) => event.cityId === cityId)
}

export function getUpcomingEvents(): RallyEvent[] {
  const now = new Date()
  return events
    .filter((event) => new Date(event.date) >= now)
    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime())
}
