/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitiesIndexRouteImport } from './routes/cities/index'
import { Route as CitiesCityIdIndexRouteImport } from './routes/cities/$cityId/index'
import { Route as CitiesCityIdEventsEventIdRouteImport } from './routes/cities/$cityId/events/$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesIndexRoute = CitiesIndexRouteImport.update({
  id: '/cities/',
  path: '/cities/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesCityIdIndexRoute = CitiesCityIdIndexRouteImport.update({
  id: '/cities/$cityId/',
  path: '/cities/$cityId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesCityIdEventsEventIdRoute =
  CitiesCityIdEventsEventIdRouteImport.update({
    id: '/cities/$cityId/events/$eventId',
    path: '/cities/$cityId/events/$eventId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cities/': typeof CitiesIndexRoute
  '/cities/$cityId/': typeof CitiesCityIdIndexRoute
  '/cities/$cityId/events/$eventId': typeof CitiesCityIdEventsEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cities': typeof CitiesIndexRoute
  '/cities/$cityId': typeof CitiesCityIdIndexRoute
  '/cities/$cityId/events/$eventId': typeof CitiesCityIdEventsEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cities/': typeof CitiesIndexRoute
  '/cities/$cityId/': typeof CitiesCityIdIndexRoute
  '/cities/$cityId/events/$eventId': typeof CitiesCityIdEventsEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cities/'
    | '/cities/$cityId/'
    | '/cities/$cityId/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cities' | '/cities/$cityId' | '/cities/$cityId/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/cities/'
    | '/cities/$cityId/'
    | '/cities/$cityId/events/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitiesIndexRoute: typeof CitiesIndexRoute
  CitiesCityIdIndexRoute: typeof CitiesCityIdIndexRoute
  CitiesCityIdEventsEventIdRoute: typeof CitiesCityIdEventsEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/': {
      id: '/cities/'
      path: '/cities'
      fullPath: '/cities/'
      preLoaderRoute: typeof CitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$cityId/': {
      id: '/cities/$cityId/'
      path: '/cities/$cityId'
      fullPath: '/cities/$cityId/'
      preLoaderRoute: typeof CitiesCityIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$cityId/events/$eventId': {
      id: '/cities/$cityId/events/$eventId'
      path: '/cities/$cityId/events/$eventId'
      fullPath: '/cities/$cityId/events/$eventId'
      preLoaderRoute: typeof CitiesCityIdEventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitiesIndexRoute: CitiesIndexRoute,
  CitiesCityIdIndexRoute: CitiesCityIdIndexRoute,
  CitiesCityIdEventsEventIdRoute: CitiesCityIdEventsEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
