/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitEventRouteImport } from './routes/submit-event'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as CitiesIndexRouteImport } from './routes/cities/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as CitiesCityIdIndexRouteImport } from './routes/cities/$cityId/index'
import { Route as CitiesCityIdEventsEventIdRouteImport } from './routes/cities/$cityId/events/$eventId'

const SubmitEventRoute = SubmitEventRouteImport.update({
  id: '/submit-event',
  path: '/submit-event',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesIndexRoute = CitiesIndexRouteImport.update({
  id: '/cities/',
  path: '/cities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesCityIdIndexRoute = CitiesCityIdIndexRouteImport.update({
  id: '/cities/$cityId/',
  path: '/cities/$cityId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesCityIdEventsEventIdRoute =
  CitiesCityIdEventsEventIdRouteImport.update({
    id: '/cities/$cityId/events/$eventId',
    path: '/cities/$cityId/events/$eventId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/submit-event': typeof SubmitEventRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/cities/': typeof CitiesIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/news/': typeof NewsIndexRoute
  '/cities/$cityId/': typeof CitiesCityIdIndexRoute
  '/cities/$cityId/events/$eventId': typeof CitiesCityIdEventsEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/submit-event': typeof SubmitEventRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/cities': typeof CitiesIndexRoute
  '/history': typeof HistoryIndexRoute
  '/news': typeof NewsIndexRoute
  '/cities/$cityId': typeof CitiesCityIdIndexRoute
  '/cities/$cityId/events/$eventId': typeof CitiesCityIdEventsEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/submit-event': typeof SubmitEventRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/cities/': typeof CitiesIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/news/': typeof NewsIndexRoute
  '/cities/$cityId/': typeof CitiesCityIdIndexRoute
  '/cities/$cityId/events/$eventId': typeof CitiesCityIdEventsEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/submit-event'
    | '/articles/$slug'
    | '/news/$slug'
    | '/articles/'
    | '/cities/'
    | '/history/'
    | '/news/'
    | '/cities/$cityId/'
    | '/cities/$cityId/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/submit-event'
    | '/articles/$slug'
    | '/news/$slug'
    | '/articles'
    | '/cities'
    | '/history'
    | '/news'
    | '/cities/$cityId'
    | '/cities/$cityId/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/submit-event'
    | '/articles/$slug'
    | '/news/$slug'
    | '/articles/'
    | '/cities/'
    | '/history/'
    | '/news/'
    | '/cities/$cityId/'
    | '/cities/$cityId/events/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SubmitEventRoute: typeof SubmitEventRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  CitiesIndexRoute: typeof CitiesIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  CitiesCityIdIndexRoute: typeof CitiesCityIdIndexRoute
  CitiesCityIdEventsEventIdRoute: typeof CitiesCityIdEventsEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit-event': {
      id: '/submit-event'
      path: '/submit-event'
      fullPath: '/submit-event'
      preLoaderRoute: typeof SubmitEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/': {
      id: '/cities/'
      path: '/cities'
      fullPath: '/cities/'
      preLoaderRoute: typeof CitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$cityId/': {
      id: '/cities/$cityId/'
      path: '/cities/$cityId'
      fullPath: '/cities/$cityId/'
      preLoaderRoute: typeof CitiesCityIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$cityId/events/$eventId': {
      id: '/cities/$cityId/events/$eventId'
      path: '/cities/$cityId/events/$eventId'
      fullPath: '/cities/$cityId/events/$eventId'
      preLoaderRoute: typeof CitiesCityIdEventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SubmitEventRoute: SubmitEventRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  CitiesIndexRoute: CitiesIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  CitiesCityIdIndexRoute: CitiesCityIdIndexRoute,
  CitiesCityIdEventsEventIdRoute: CitiesCityIdEventsEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
